### ISSUE TITLE
Recognition Parameters

### ISSUE THREAD

**Issue by toktarov84** [freeletics/libdmtx-mobile#1]
Hello,
The Python version of method decode(..) has many parameters.
> dm_info = decode(prep, timeout=5, max_count=1, shrink=3, shape=2, threshold=0)

The Python version parameters from pylibdmtx.py:
> def decode(image, timeout=None, gap_size=None, shrink=1, shape=None,
           deviation=None, threshold=None, min_edge=None, max_edge=None,
           corrections=None, max_count=None):

> Args:
>         image: "numpy.ndarray", "PIL.Image" or tuple (pixels, width, height)
>         timeout (int): milliseconds
>         gap_size (int):
>         shrink (int):
>         shape (int):
>         deviation (int):
>         threshold (int):
>         min_edge (int):
>         max_edge (int):
>         corrections (int):
>         max_count (int): stop after reading this many barcodes. "None" to read
>             as many as possible.

But I have a problem with Android Mobile version. 
I need to change shrink, shape, threshold. 

> DMTXImage dmtxImage = new DMTXImage(camWidth, camHeight, dmtxBufferArray);
> DMTXTag[] tags = dmtxImage.getTags(1, 1);

Is there any way I can change these parameters?
Thanks

**Comment by kboyarshinov** [comment]
Android and iOS versions use [C API](https://github.com/dmtx/libdmtx/blob/master/dmtx.h) directly. You'd have to update [JNI interface](https://github.com/freeletics/libdmtx-mobile/blob/main/libdmtx-android/jni/org_libdmtx_DMTXImage.c) to pass [these properties](https://github.com/NaturalHistoryMuseum/pylibdmtx/blob/master/pylibdmtx/pylibdmtx.py#L268-L273) to a decoder.
